---

mysql_port: 3306
mysql_bind_address: "0.0.0.0"
mysql_root_db_pass: secret

db_master: 54.161.207.117
db_slave: 3.88.66.16

ansible_os_family: Ubuntu

mysql_db:
  - name: example_db1
    replicate: yes
  - name: example_db2
    replicate: no

mysql_users:
  - name: user1
    pass: verystrong
    priv: "*.*:ALL"

mysql_repl_user:
  - name: repl
    pass: verystrong
    priv: '*.*:REPLICATION SLAVE,REPLICATION CLIENT'

mysql_repl_role: master
mysql_db_id: 7

mysql_sql_mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

mysql_add_engine: false
mysql_engines: []

mysql_extra_packages_deb: []
mysql_extra_packages_rh: []
