---
- hosts: db_master
  roles:
    - { role: mysql,
              mysql_db: [{ name: example_db1 },
                        { name: example_db1 }],
              mysql_users: [{ name: user1, pass: verystrong, priv: "*.*:ALL" },
                            { name: user2, pass: verystrongtoo }],             
              mysql_db_id: 8 }

- hosts: db_slave
  roles:
    - { role: mysql,
              mysql_db: none,
              mysql_users: none,
              mysql_repl_role: slave,
              mysql_repl_master: 54.161.207.117,           
              mysql_users: [{ name: slave_user1, pass: verystrong, priv: "*.*:ALL" },
                            { name: slave_user2, pass: verystrongtoo }],
              mysql_db_id: 9,
              mysql_repl_user: [{ name: repl, pass: verystrong }] }
